version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./backend/data/qdrant_data:/qdrant/storage
  
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - '7700:7700'
    environment:
      MEILI_MASTER_KEY: 'simple_password'
    volumes:
      - ./backend/data/meili:/meili_data

  backend-server:
    image: mori:latest
    env_file:
    - .env
    expose:
    - "5001"
    depends_on:
    - qdrant
    - elasticsearch
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any

  nginx:
    image: nginx
    volumes:
    - ./backend/nginx/nginx.conf:/tmp/nginx.conf 
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
    - 5001:4000
    depends_on:
    - backend-server
