version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./backend/data/qdrant_data:/qdrant/storage
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - ./backend/data/elasticsearch:/usr/share/elasticsearch/data

  backend-server:
    image: mori:latest
    env_file:
    - .env
    expose:
    - "5001"
    depends_on:
    - qdrant
    - elasticsearch
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: any

  nginx:
    image: nginx
    volumes:
    - ./backend/nginx/nginx.conf:/tmp/nginx.conf 
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
    - 5001:4000
    depends_on:
    - backend-server
